-- CertVault: certificate hosting and verification
-- Organizations (clubs) issue certificates; CertVault generates IDs and hosts records.

-- Organizations (clubs) that can issue certificates
CREATE TABLE IF NOT EXISTS public.certvault_organizations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  slug TEXT UNIQUE,
  email TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_certvault_organizations_email ON public.certvault_organizations(email);
CREATE INDEX IF NOT EXISTS idx_certvault_organizations_slug ON public.certvault_organizations(slug);

-- Events (each certificate must belong to an event)
CREATE TABLE IF NOT EXISTS public.certvault_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES public.certvault_organizations(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  event_date DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_certvault_events_organization ON public.certvault_events(organization_id);

-- Certificates: IDs generated by CertVault, not editable by clubs
CREATE TABLE IF NOT EXISTS public.certvault_certificates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  certificate_id TEXT NOT NULL UNIQUE,  -- Unique ID generated by CertVault (e.g. CV-xxxx-xxxx)
  event_id UUID NOT NULL REFERENCES public.certvault_events(id) ON DELETE CASCADE,
  organization_id UUID NOT NULL REFERENCES public.certvault_organizations(id) ON DELETE CASCADE,
  recipient_name TEXT NOT NULL,
  recipient_email TEXT,
  category TEXT NOT NULL DEFAULT 'Participant',  -- Participant, Winner, Organizer, etc.
  date_issued DATE NOT NULL DEFAULT CURRENT_DATE,
  status TEXT NOT NULL DEFAULT 'valid' CHECK (status IN ('valid', 'revoked')),
  pdf_url TEXT,  -- Cloudinary secure_url (HTTPS CDN link)
  cloudinary_public_id TEXT,  -- Cloudinary public_id for deletion/management
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_certvault_certificates_certificate_id ON public.certvault_certificates(certificate_id);
CREATE INDEX IF NOT EXISTS idx_certvault_certificates_event ON public.certvault_certificates(event_id);
CREATE INDEX IF NOT EXISTS idx_certvault_certificates_organization ON public.certvault_certificates(organization_id);
CREATE INDEX IF NOT EXISTS idx_certvault_certificates_status ON public.certvault_certificates(status);

-- RLS: certificates table readable by anon for verification; write only via service_role / backend
ALTER TABLE public.certvault_certificates ENABLE ROW LEVEL SECURITY;
-- Policy: allow public SELECT by certificate_id for verification (or use API-only and keep anon revoked)
REVOKE ALL ON public.certvault_certificates FROM anon;
REVOKE ALL ON public.certvault_certificates FROM authenticated;
GRANT ALL ON public.certvault_certificates TO service_role;

-- Organizations and events: backend-only (service_role)
ALTER TABLE public.certvault_organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certvault_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.certvault_organizations FROM anon;
REVOKE ALL ON public.certvault_organizations FROM authenticated;
REVOKE ALL ON public.certvault_events FROM anon;
REVOKE ALL ON public.certvault_events FROM authenticated;
GRANT ALL ON public.certvault_organizations TO service_role;
GRANT ALL ON public.certvault_events TO service_role;

COMMENT ON TABLE public.certvault_certificates IS 'CertVault: certificates issued by organizations. Certificate IDs generated by platform. Hosted & verified via CertVault.';
COMMENT ON COLUMN public.certvault_certificates.certificate_id IS 'Unique ID generated by CertVault; used for public verification.';
